#!/bin/bash
echo 'вавыавы'

run_sql_c() {
local call="$1"

if [! -f ""]; then

echo "Такого файла не существует"

else
psql -U postgres -d lab2 -f "$file_path"
echo "Скрипт выполнен"
fi
}

run_sql_c "$1, $2"
